[project]
name = "selenelang"
version = "0.9.0"
module = "github.com/selene-lang/selenelang"
entry = "cmd/selene"

[docs]
paths = ["docs", "README.md"]

[examples]
roots = ["examples"]

[dependencies]
"github.com/selene-lang/richmath" = { version = "v1.0.0", source = "https://github.com/selene-lang/richmath" }
